version: "3.9"
services:
  app:
    image: golang:latest
    container_name: go_app
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    command: ["tail", "-f", "/dev/null"]

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
